# : Manager [[[

[mgr]
cwd = { fg = "#ffffff" }

# Tab
tab_active = { fg = "#000000", bg = "#ebbcba", bold = true }
tab_inactive = { fg = "#7e1f1b", bg = "#ffffff" }
tab_width = 1

# Find
find_keyword = { fg = "#eb6f92", bold = true, italic = true, underline = true }
find_position = { fg = "#eb6f92", bold = true, italic = true }

# Marker
marker_copied = { fg = "#123848", bg = "#123848" }
marker_cut = { fg = "#123848", bg = "#123848" }
marker_marked = { fg = "#eb6f92", bg = "#eb6f92" }
marker_selected = { fg = "#31748f", bg = "#31748f" }

# Count
count_copied = { fg = "#ffffff", bg = "#123848" }
count_cut = { fg = "#ffffff", bg = "#123848" }
count_selected = { fg = "#000000", bg = "#31748f" }

# Border
border_style  = { fg = "#ebbcba" }

# : ]]]


# : Status [[[

[status]
separator_style = { bg = "#000000", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ebbcba", fg = "#000000", bold = true }
normal_alt  = { bg = "#242134", fg = "#ffffff" }

# Select mode
select_main = { bg = "#9ccfd8", fg = "#000000", bold = true }
select_alt  = { bg = "#242134", fg = "#ffffff" }

# Unset mode
unset_main = { bg = "#31748f", fg = "#ffffff", bold = true }
unset_alt  = { bg = "#242134", fg = "#ffffff" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ebbcba", bg = "#191724" }
progress_error = { fg = "#eb6f92", bg = "#191724" }

# Permissions
permissions_t = { fg = "#9ccfd8" }
permissions_w = { fg = "#31748f" }
permissions_x = { fg = "#eb6f92" }
permissions_r = { fg = "#123848" }
permissions_s = { fg = "#7e1f1b" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ebbcba" }
active = { fg = "#31748f", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ebbcba" }
value = { fg = "#ffffff" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ebbcba", bold = true, bg = "#191724" }
inactive = { fg = "#9ccfd8", bg = "#191724" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ebbcba", bg = "#000000" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ebbcba" }
title = {}
hovered = { fg = "#123848", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#191724" }
cand = { fg = "#ebbcba" }
rest = { fg = "#000000" }
desc = { fg = "#ffffff" }
separator = " â–¶ "
separator_style = { fg = "#ffffff" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ffffff" }
run = { fg = "#ffffff" }
footer = { fg = "#000000", bg = "#9ccfd8" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#31748f" }
title_warn = { fg = "#ebbcba" }
title_error = { fg = "#eb6f92" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#8e0b30" },
    { name = "*", is = "exec", fg = "#ffffff" },

    # Fallback
    { name = "*", fg = "#ffffff" },
    { name = "*/", fg = "#ebbcba" },
]

# : ]]]
