# : Manager [[[

[mgr]
cwd = { fg = "#e4e2e5" }

# Tab
tab_active = { fg = "#1d3051", bg = "#b4c7f0", bold = true }
tab_inactive = { fg = "#d7e2ff", bg = "#051b3b" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff70ee", bg = "#ff70ee" }
marker_cut = { fg = "#ffd6fa", bg = "#ffd6fa" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e4b9e0", bg = "#e4b9e0" }

# Count
count_copied = { fg = "#2c112e", bg = "#ffd6fa" }
count_cut = { fg = "#2c112e", bg = "#ffd6fa" }
count_selected = { fg = "#1d3051", bg = "#e4b9e0" }

# Border
border_symbol = " "
border_style  = { fg = "#b4c7f0" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#1d3051", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#b4c7f0", fg = "#1d3051", bold = true }
normal_alt  = { bg = "#44474e", fg = "#c5c6cf" }

# Select mode
select_main = { bg = "#c0c6d8", fg = "#2a303e", bold = true }
select_alt  = { bg = "#44474e", fg = "#c5c6cf" }

# Unset mode
unset_main = { bg = "#e4b9e0", fg = "#442644", bold = true }
unset_alt  = { bg = "#44474e", fg = "#c5c6cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#b4c7f0", bg = "#39393c" }
progress_error = { fg = "#ffb4ab", bg = "#39393c" }

# Permissions
permissions_t = { fg = "#62719e" }
permissions_w = { fg = "#b94baf" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff3de7" }
permissions_s = { fg = "#3e73ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#b4c7f0" }
active = { fg = "#e4b9e0", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#b4c7f0" }
value = { fg = "#e4e2e5" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#b4c7f0", bg = "#1d3051" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#b4c7f0" }
title = {}
hovered = { fg = "#ffd6fa", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#39393c" }
cand = { fg = "#b4c7f0" }
rest = { fg = "#1d3051" }
desc = { fg = "#e4e2e5" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e4e2e5" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e4e2e5" }
run = { fg = "#e4e2e5" }
footer = { fg = "#2a303e", bg = "#c0c6d8" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e4b9e0" }
title_warn = { fg = "#b4c7f0" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e4e2e5" },
    { name = "*/", fg = "#b4c7f0" },
]

# : ]]]
