[config]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
#[templates.placeholder]
#input_path = "/home/elrond/.config/quickshell/Assets/MatugenTemplates/noctalia.json"
#output_path = "/home/elrond/.cache/noctalia/placeholder.json"

[templates.hyprland]
input_path = '~/.config/noctalia/matugenTemplates/hyprland-colors.conf'
output_path = '~/.config/hypr/noctalia/noctalia-colors.conf'
post_hook = 'hyprctl reload'
